### PR TITLE
Support for connecting to random VPN server.

### PR DESCRIPTION
**Pull request by mikijov**
This PR adds support for connecting to random server. I have chosen to change behaviour of the SERVER and COUNTRY variables, so that random server is chosen if neither is specified. If you prefer, I can change the code to connect to random server if COUNTRY is set to magic value `RANDOM`.

### CODE REVIEW

**Comment by tprasadtp** [comment]
Hello thanks for this PR. I would prefer user explicitly specifies that they wish to connect to to random server. So could you please update the PR and I will be happy to merge once its done

**Comment by tprasadtp** [comment]
On an additional note, I would prefer if `PROTONVPN_SERVER` accepts special value `RANDOM` rather than COUNTRY. Though it should not matter but just to match the protonvpncli.

**Comment by mikijov** [comment]
OK, that should do it.

**Comment by tprasadtp** [comment]
included in 52082016e84d114d26f739c844c6e52cb9a98cfb.

**Pull request closed without merging**
