### PR TITLE
Bump cli to 2.2.4

### PR DESCRIPTION
**Pull request by hadim**

### CODE REVIEW

**Comment by tprasadtp** [comment]
Hello @hadim, 
Thank you for the PR. Under the hood protonvpv cli has changed the way it handles openvpn config files. Now they are using jinja2 templates to generate them. I will take a look at this PR over the weekend and test it a bit so that it does not break anything.

**Comment by hadim** [comment]
Friendly bump here !

**Comment by tprasadtp** [comment]
This PR doesn't (yet) take into consideration the internal changes of protonvpn-cli. As I said earlier The new version of cli uses jinja for templating. configuration files and scripts be updated to accommodate such a change. Bumping just the cli to latest version from upstream might lead to breaking changes.

What needs to be done

- [ ] - Remove included template and let protonvpn generate templates on every fresh start/restart of vpn
- [ ] Update to accommodate credentials config changes

**Comment by tprasadtp** [comment]
closing in favor of #8

**Pull request closed without merging**
